use http::Uri;
use http::header::{HeaderMap, SET_COOKIE};
use std::net::IpAddr;
use std::path::PathBuf;
use std::sync::RwLock;

/// A cookie jar that can optionally persist cookies to a file
pub struct CookieJar {
    /// Stored cookies as "name=value" pairs per domain
    cookies: RwLock<Vec<StoredCookie>>,
    file_path: Option<PathBuf>,
    /// Track if we need to save on drop
    modified: RwLock<bool>,
}

struct StoredCookie {
    domain: String,
    path: String,
    secure: bool,
    name: String,
    value: String,
}

impl CookieJar {
    pub fn new(file_path: Option<PathBuf>) -> Self {
        let mut cookies = Vec::new();

        // Load existing cookies from file if it exists
        if let Some(ref path) = file_path
            && path.exists()
            && let Ok(content) = std::fs::read_to_string(path)
        {
            for line in content.lines() {
                if line.starts_with('#') || line.trim().is_empty() {
                    continue;
                }
                if let Some(cookie) = parse_netscape_cookie_line(line) {
                    cookies.push(cookie);
                }
            }
        }

        Self {
            cookies: RwLock::new(cookies),
            file_path,
            modified: RwLock::new(false),
        }
    }

    /// Store cookies from Set-Cookie response headers
    pub fn store_response_cookies(&self, headers: &HeaderMap, uri: &Uri) {
        let Some(host) = normalize_host(uri.host().unwrap_or("")) else {
            return;
        };
        let path = uri.path();

        let mut cookies = self.cookies.write().unwrap_or_else(|e| e.into_inner());
        let mut stored_any = false;

        for cookie_header in headers.get_all(SET_COOKIE) {
            if let Ok(cookie_str) = cookie_header.to_str() {
                let Some((name, value)) = cookie_str
                    .split(';')
                    .next()
                    .and_then(|name_value| name_value.split_once('='))
                else {
                    continue;
                };

                let Some(cookie_domain) = derive_cookie_domain(&host, cookie_str) else {
                    continue;
                };

                let secure = has_secure_attr(cookie_str);
                let cookie_path = extract_cookie_attr(cookie_str, "path")
                    .filter(|p| !p.trim().is_empty())
                    .unwrap_or_else(|| path.to_string());

                if name.trim().is_empty() {
                    continue;
                }

                cookies.push(StoredCookie {
                    domain: cookie_domain,
                    path: cookie_path,
                    secure,
                    name: name.trim().to_string(),
                    value: value.trim().to_string(),
                });
                stored_any = true;
            }
        }

        if stored_any {
            *self.modified.write().unwrap_or_else(|e| e.into_inner()) = true;
        }
    }

    /// Save cookies to file (called on drop if file_path is set)
    pub fn save_to_file(&self) {
        let Some(ref path) = self.file_path else {
            return;
        };

        let cookies = self.cookies.read().unwrap_or_else(|e| e.into_inner());
        let mut content = String::from(
            "# Netscape HTTP Cookie File\n# https://curl.se/docs/http-cookies.html\n# This file was generated by orb\n\n",
        );

        for cookie in cookies.iter() {
            // Format: domain, flag, path, secure, expiry, name, value
            let domain_flag = if cookie.domain.starts_with('.') {
                "TRUE"
            } else {
                "FALSE"
            };
            let secure_flag = if cookie.secure { "TRUE" } else { "FALSE" };
            content.push_str(&format!(
                "{}\t{}\t{}\t{}\t0\t{}\t{}\n",
                cookie.domain, domain_flag, cookie.path, secure_flag, cookie.name, cookie.value
            ));
        }

        if let Err(err) = std::fs::write(path, content) {
            eprintln!(
                "Warning: Failed to write cookie jar '{}': {}",
                path.display(),
                err
            );
        }
    }
}

impl Drop for CookieJar {
    fn drop(&mut self) {
        if self.file_path.is_some() && *self.modified.read().unwrap_or_else(|e| e.into_inner()) {
            self.save_to_file();
        }
    }
}

/// Extract a cookie attribute value
fn extract_cookie_attr(cookie_str: &str, attr: &str) -> Option<String> {
    let attr_lower = attr.to_lowercase();

    for part in cookie_str.split(';') {
        let part_trimmed = part.trim();
        let part_lower = part_trimmed.to_lowercase();
        if part_lower.starts_with(&format!("{}=", attr_lower)) {
            return part_trimmed
                .split_once('=')
                .map(|(_, v)| v.trim().to_string());
        }
    }
    None
}

fn has_secure_attr(cookie_str: &str) -> bool {
    cookie_str
        .split(';')
        .skip(1)
        .any(|part| part.trim().eq_ignore_ascii_case("secure"))
}

fn normalize_host(host: &str) -> Option<String> {
    let host = host.trim().trim_end_matches('.').to_ascii_lowercase();
    if host.is_empty() { None } else { Some(host) }
}

fn is_domain_match(host: &str, domain: &str) -> bool {
    host == domain || host.ends_with(&format!(".{}", domain))
}

fn derive_cookie_domain(host: &str, cookie_str: &str) -> Option<String> {
    let domain_attr = extract_cookie_attr(cookie_str, "domain");
    let Some(raw_domain) = domain_attr else {
        return Some(host.to_string()); // host-only cookie
    };

    let domain = raw_domain
        .trim()
        .trim_start_matches('.')
        .trim_end_matches('.')
        .to_ascii_lowercase();

    if domain.is_empty() {
        return None;
    }

    // Domain attribute cookies are only valid for DNS hostnames.
    if host.parse::<IpAddr>().is_ok() || domain.parse::<IpAddr>().is_ok() {
        return None;
    }

    // Response origin must domain-match the requested cookie domain.
    if !is_domain_match(host, &domain) {
        return None;
    }

    // Reject public suffixes (e.g. ".com", ".co.uk").
    psl::domain_str(&domain)?;

    // Domain cookies apply to subdomains as well.
    Some(format!(".{}", domain))
}

/// Parse a line from Netscape cookie file format
/// Format: domain\tflag\tpath\tsecure\texpiry\tname\tvalue
fn parse_netscape_cookie_line(line: &str) -> Option<StoredCookie> {
    let parts: Vec<&str> = line.split('\t').collect();
    if parts.len() < 7 {
        return None;
    }

    let mut domain = parts[0].to_string();
    let domain_flag = parts[1] == "TRUE";
    if domain_flag && !domain.starts_with('.') {
        domain = format!(".{}", domain);
    }
    let path = parts[2].to_string();
    let secure = parts[3] == "TRUE";
    let name = parts[5].to_string();
    let value = parts[6].to_string();

    Some(StoredCookie {
        domain,
        path,
        secure,
        name,
        value,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use http::HeaderValue;

    fn headers_with_set_cookie(cookie: &str) -> HeaderMap {
        let mut headers = HeaderMap::new();
        headers.insert(SET_COOKIE, HeaderValue::from_str(cookie).unwrap());
        headers
    }

    fn stored_domains(jar: &CookieJar) -> Vec<String> {
        jar.cookies
            .read()
            .unwrap_or_else(|e| e.into_inner())
            .iter()
            .map(|c| c.domain.clone())
            .collect::<Vec<_>>()
    }

    #[test]
    fn test_store_host_only_cookie_uses_origin_host() {
        let jar = CookieJar::new(None);
        let uri: Uri = "http://sub.example.com/test".parse().unwrap();
        let headers = headers_with_set_cookie("session=abc; Path=/");

        jar.store_response_cookies(&headers, &uri);

        assert_eq!(stored_domains(&jar), vec!["sub.example.com"]);
    }

    #[test]
    fn test_store_domain_cookie_for_parent_domain() {
        let jar = CookieJar::new(None);
        let uri: Uri = "http://sub.example.com/test".parse().unwrap();
        let headers = headers_with_set_cookie("session=abc; Domain=.example.com; Path=/");

        jar.store_response_cookies(&headers, &uri);

        assert_eq!(stored_domains(&jar), vec![".example.com"]);
    }

    #[test]
    fn test_reject_domain_cookie_for_unrelated_domain() {
        let jar = CookieJar::new(None);
        let uri: Uri = "http://attacker.com/test".parse().unwrap();
        let headers = headers_with_set_cookie("session=abc; Domain=.example.com; Path=/");

        jar.store_response_cookies(&headers, &uri);

        assert!(stored_domains(&jar).is_empty());
    }

    #[test]
    fn test_reject_domain_cookie_for_public_suffix() {
        let jar = CookieJar::new(None);
        let uri: Uri = "http://example.com/test".parse().unwrap();
        let headers = headers_with_set_cookie("session=abc; Domain=.com; Path=/");

        jar.store_response_cookies(&headers, &uri);

        assert!(stored_domains(&jar).is_empty());
    }

    #[test]
    fn test_reject_domain_cookie_for_mixed_case_public_suffix() {
        let jar = CookieJar::new(None);
        let uri: Uri = "http://curl.co.uk/test".parse().unwrap();
        let headers = headers_with_set_cookie("session=abc; Domain=Co.UK; Path=/");

        jar.store_response_cookies(&headers, &uri);

        assert!(stored_domains(&jar).is_empty());
    }

    #[test]
    fn test_reject_domain_cookie_for_ip_host() {
        let jar = CookieJar::new(None);
        let uri: Uri = "http://127.0.0.1/test".parse().unwrap();
        let headers = headers_with_set_cookie("session=abc; Domain=.example.com; Path=/");

        jar.store_response_cookies(&headers, &uri);

        assert!(stored_domains(&jar).is_empty());
    }

    #[test]
    fn test_reject_ip_address_domain_attribute() {
        let jar = CookieJar::new(None);
        let uri: Uri = "http://example.com/test".parse().unwrap();
        let headers = headers_with_set_cookie("session=abc; Domain=127.0.0.1; Path=/");

        jar.store_response_cookies(&headers, &uri);

        assert!(stored_domains(&jar).is_empty());
    }

    #[test]
    fn test_parse_netscape_cookie_line_honors_domain_flag() {
        let cookie =
            parse_netscape_cookie_line("example.com\tTRUE\t/\tFALSE\t0\tsession\tabc123").unwrap();

        assert_eq!(cookie.domain, ".example.com");
    }

    #[test]
    fn test_parse_netscape_cookie_line_with_long_value() {
        let long_value = "x".repeat(20_000);
        let line = format!(".example.com\tTRUE\t/\tFALSE\t0\tsession\t{}", long_value);
        let cookie = parse_netscape_cookie_line(&line).unwrap();
        assert_eq!(cookie.value.len(), 20_000);
    }
}
